Repository nutti/fake-bpy-module, pull requests merged in 2024-05, with the labels that each got.

#206 Update: Support for Blender v4.1
  .github/workflows/fake-bpy-module-ci.yml
  README.md
  src/fake_bpy_module/analyzer/directives.py
  src/fake_bpy_module/support.py
  tests/pylint_cycles.sh
  tools/pip_package/build_pip_package.sh
  tools/utils/download_blender.sh
Labels: enhancement

#208 Update Python Version for local gen_module
  docs/generate_modules.md
  tools/gen_module/Dockerfile
Labels: bug

#215 Fix: generate only needed py.typed
  src/fake_bpy_module/generator/generator.py
Labels: bug

#214 Fix: remove extra quotes from set default value
  src/fake_bpy_module/analyzer/directives.py
Labels: bug

#207 Use modern Python 3.10 syntax
  src/fake_bpy_module/generator/writers.py
  src/fake_bpy_module/transformer/bpy_ops_override_parameters_adder.py
  src/fake_bpy_module/transformer/data_type_refiner.py
  src/fake_bpy_module/transformer/default_value_filler.py
  src/mods/common/analyzer/append/bpy.types.mod.rst
  src/mods/common/analyzer/new/bpy.types.mod.rst
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/expect/class/class.json
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/expect/class/class.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/input/class/class.rst
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/class/class.py
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/class/class.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/function/function.py
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/input/class/class.rst
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/class/class.pyi
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/class/class.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/function/function.pyi
  tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/input/class/class.rst
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/bpy_ops_override_parameters_adder_test/expect/basic_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/special_data_type_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/input/basic.rst
Labels: enhancement

#217 Fix: enum regexes to refine data types
  src/fake_bpy_module/transformer/data_type_refiner.py
Labels: bug

#218 Fix: use str only for enum types instead of str|int
  src/fake_bpy_module/transformer/data_type_refiner.py
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
Labels: enhancement

#222 Fix typing.Tuple syntax reintroduced in mod file
  src/mods/common/analyzer/update/bpy.app.mod.rst
Labels: bug

#225 Fix bpy_prop_collection.items missing return type
  src/mods/common/analyzer/update/bpy.types.mod.rst
Labels: bug

#229 Fix bpy_prop_array.foreach_get/set arguments
  src/mods/common/analyzer/new/bpy.types.mod.rst
Labels: bug

#233 __delitem__ should return None
  src/mods/common/analyzer/append/bpy.types.mod.rst
  src/mods/common/analyzer/new/bpy.types.mod.rst
Labels: bug

#223 Replace deprecated aliases to ABCs in collections.abc
  src/fake_bpy_module/transformer/data_type_refiner.py
  src/fake_bpy_module/transformer/default_value_filler.py
  src/mods/common/analyzer/append/bpy.types.mod.rst
  src/mods/common/analyzer/new/bpy.types.mod.rst
  src/mods/common/analyzer/update/bpy.app.timers.mod.rst
  src/mods/common/analyzer/update/bpy.types.mod.rst
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/input/basic.rst
Labels: enhancement

#232 Fix BMesh typing (#179)
  src/mods/common/analyzer/append/bmesh.types.mod.rst
  src/mods/common/analyzer/update/bmesh.types.mod.rst
Labels: bug

#237 fix building instructions
  docs/generate_modules.md
  src/gen_modfile/gen_bgl_modfile.py
Labels: documentation
