Repository nutti/fake-bpy-module, pull requests merged in 2025-01, with the labels that each got.

#334 Fix bpy.typing confused as std typing
  src/fake_bpy_module/generator/writers.py
  src/fake_bpy_module/transformer/data_type_refiner.py
  src/fake_bpy_module/transformer/rna_enum_converter.py
  tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_2/__init__.py
  tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_2/__init__.pyi
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/description_dependency_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
  tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/rna_enum_converter_test/expect/basic_transformed.xml
Labels: bug

#335 Update vscode config
  docs/setup_visual_studio_code.md
Labels: documentation

#339 Fix: mathutils classes to support slice assignment of themselves #336
  src/mods/common/analyzer/append/mathutils.mod.rst
Labels: bug

#340 Add bpy_prop_collection_idprop mods
  src/fake_bpy_module/generator/writers.py
  src/mods/common/analyzer/append/bpy.types.mod.rst
  src/mods/common/analyzer/update/bpy.types.mod.rst
Labels: enhancement

#343 Use _GenericType1 for bpy_prop_collection_idprop.add() return type
  src/mods/common/analyzer/update/bpy.types.mod.rst
Labels: enhancement
